title: Blogs
author: Anchit Gupta
email: anchit19060@iiitd.ac.in
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  Portfolio

# social links
twitter_username: AchiAnchit # DO NOT include the @ character, or else the build will fail!
github_username:  anchitgupt # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
